// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.junipermist.device.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.junipermist.device.outputs.GatewayTunnelConfigsAutoProvisionLatlng;
import com.pulumi.junipermist.device.outputs.GatewayTunnelConfigsAutoProvisionPrimary;
import com.pulumi.junipermist.device.outputs.GatewayTunnelConfigsAutoProvisionSecondary;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GatewayTunnelConfigsAutoProvision {
    private @Nullable Boolean enable;
    /**
     * @return API override for POP selection
     * 
     */
    private @Nullable GatewayTunnelConfigsAutoProvisionLatlng latlng;
    private @Nullable GatewayTunnelConfigsAutoProvisionPrimary primary;
    /**
     * @return enum: `jse-ipsec`, `zscaler-ipsec`
     * 
     */
    private String provider;
    /**
     * @return API override for POP selection in the case user wants to override the auto discovery of remote network location and force the tunnel to use the specified peer location.
     * 
     */
    private @Nullable String region;
    private @Nullable GatewayTunnelConfigsAutoProvisionSecondary secondary;
    /**
     * @return if `provider`==`prisma-ipsec`. By default, we&#39;ll use the location of the site to determine the optimal Remote Network location, optionally, service_connection can be considered, then we&#39;ll also consider this along with the site location. Define service_connection if the traffic is to be routed to a specific service connection. This field takes a service connection name that is configured in the Prisma cloud, Prisma Access Setup &gt; Service Connections.
     * 
     */
    private @Nullable String serviceConnection;

    private GatewayTunnelConfigsAutoProvision() {}
    public Optional<Boolean> enable() {
        return Optional.ofNullable(this.enable);
    }
    /**
     * @return API override for POP selection
     * 
     */
    public Optional<GatewayTunnelConfigsAutoProvisionLatlng> latlng() {
        return Optional.ofNullable(this.latlng);
    }
    public Optional<GatewayTunnelConfigsAutoProvisionPrimary> primary() {
        return Optional.ofNullable(this.primary);
    }
    /**
     * @return enum: `jse-ipsec`, `zscaler-ipsec`
     * 
     */
    public String provider() {
        return this.provider;
    }
    /**
     * @return API override for POP selection in the case user wants to override the auto discovery of remote network location and force the tunnel to use the specified peer location.
     * 
     */
    public Optional<String> region() {
        return Optional.ofNullable(this.region);
    }
    public Optional<GatewayTunnelConfigsAutoProvisionSecondary> secondary() {
        return Optional.ofNullable(this.secondary);
    }
    /**
     * @return if `provider`==`prisma-ipsec`. By default, we&#39;ll use the location of the site to determine the optimal Remote Network location, optionally, service_connection can be considered, then we&#39;ll also consider this along with the site location. Define service_connection if the traffic is to be routed to a specific service connection. This field takes a service connection name that is configured in the Prisma cloud, Prisma Access Setup &gt; Service Connections.
     * 
     */
    public Optional<String> serviceConnection() {
        return Optional.ofNullable(this.serviceConnection);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GatewayTunnelConfigsAutoProvision defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean enable;
        private @Nullable GatewayTunnelConfigsAutoProvisionLatlng latlng;
        private @Nullable GatewayTunnelConfigsAutoProvisionPrimary primary;
        private String provider;
        private @Nullable String region;
        private @Nullable GatewayTunnelConfigsAutoProvisionSecondary secondary;
        private @Nullable String serviceConnection;
        public Builder() {}
        public Builder(GatewayTunnelConfigsAutoProvision defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enable = defaults.enable;
    	      this.latlng = defaults.latlng;
    	      this.primary = defaults.primary;
    	      this.provider = defaults.provider;
    	      this.region = defaults.region;
    	      this.secondary = defaults.secondary;
    	      this.serviceConnection = defaults.serviceConnection;
        }

        @CustomType.Setter
        public Builder enable(@Nullable Boolean enable) {

            this.enable = enable;
            return this;
        }
        @CustomType.Setter
        public Builder latlng(@Nullable GatewayTunnelConfigsAutoProvisionLatlng latlng) {

            this.latlng = latlng;
            return this;
        }
        @CustomType.Setter
        public Builder primary(@Nullable GatewayTunnelConfigsAutoProvisionPrimary primary) {

            this.primary = primary;
            return this;
        }
        @CustomType.Setter
        public Builder provider(String provider) {
            if (provider == null) {
              throw new MissingRequiredPropertyException("GatewayTunnelConfigsAutoProvision", "provider");
            }
            this.provider = provider;
            return this;
        }
        @CustomType.Setter
        public Builder region(@Nullable String region) {

            this.region = region;
            return this;
        }
        @CustomType.Setter
        public Builder secondary(@Nullable GatewayTunnelConfigsAutoProvisionSecondary secondary) {

            this.secondary = secondary;
            return this;
        }
        @CustomType.Setter
        public Builder serviceConnection(@Nullable String serviceConnection) {

            this.serviceConnection = serviceConnection;
            return this;
        }
        public GatewayTunnelConfigsAutoProvision build() {
            final var _resultValue = new GatewayTunnelConfigsAutoProvision();
            _resultValue.enable = enable;
            _resultValue.latlng = latlng;
            _resultValue.primary = primary;
            _resultValue.provider = provider;
            _resultValue.region = region;
            _resultValue.secondary = secondary;
            _resultValue.serviceConnection = serviceConnection;
            return _resultValue;
        }
    }
}
