// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.junipermist.device.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;

@CustomType
public final class GetGatewayStatsDeviceGatewayStatSpu2Stat {
    private Integer spuCpu;
    private Integer spuCurrentSession;
    private Integer spuMaxSession;
    private Integer spuMemory;
    private Integer spuPendingSession;
    private Integer spuUptime;
    private Integer spuValidSession;

    private GetGatewayStatsDeviceGatewayStatSpu2Stat() {}
    public Integer spuCpu() {
        return this.spuCpu;
    }
    public Integer spuCurrentSession() {
        return this.spuCurrentSession;
    }
    public Integer spuMaxSession() {
        return this.spuMaxSession;
    }
    public Integer spuMemory() {
        return this.spuMemory;
    }
    public Integer spuPendingSession() {
        return this.spuPendingSession;
    }
    public Integer spuUptime() {
        return this.spuUptime;
    }
    public Integer spuValidSession() {
        return this.spuValidSession;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetGatewayStatsDeviceGatewayStatSpu2Stat defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer spuCpu;
        private Integer spuCurrentSession;
        private Integer spuMaxSession;
        private Integer spuMemory;
        private Integer spuPendingSession;
        private Integer spuUptime;
        private Integer spuValidSession;
        public Builder() {}
        public Builder(GetGatewayStatsDeviceGatewayStatSpu2Stat defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.spuCpu = defaults.spuCpu;
    	      this.spuCurrentSession = defaults.spuCurrentSession;
    	      this.spuMaxSession = defaults.spuMaxSession;
    	      this.spuMemory = defaults.spuMemory;
    	      this.spuPendingSession = defaults.spuPendingSession;
    	      this.spuUptime = defaults.spuUptime;
    	      this.spuValidSession = defaults.spuValidSession;
        }

        @CustomType.Setter
        public Builder spuCpu(Integer spuCpu) {
            if (spuCpu == null) {
              throw new MissingRequiredPropertyException("GetGatewayStatsDeviceGatewayStatSpu2Stat", "spuCpu");
            }
            this.spuCpu = spuCpu;
            return this;
        }
        @CustomType.Setter
        public Builder spuCurrentSession(Integer spuCurrentSession) {
            if (spuCurrentSession == null) {
              throw new MissingRequiredPropertyException("GetGatewayStatsDeviceGatewayStatSpu2Stat", "spuCurrentSession");
            }
            this.spuCurrentSession = spuCurrentSession;
            return this;
        }
        @CustomType.Setter
        public Builder spuMaxSession(Integer spuMaxSession) {
            if (spuMaxSession == null) {
              throw new MissingRequiredPropertyException("GetGatewayStatsDeviceGatewayStatSpu2Stat", "spuMaxSession");
            }
            this.spuMaxSession = spuMaxSession;
            return this;
        }
        @CustomType.Setter
        public Builder spuMemory(Integer spuMemory) {
            if (spuMemory == null) {
              throw new MissingRequiredPropertyException("GetGatewayStatsDeviceGatewayStatSpu2Stat", "spuMemory");
            }
            this.spuMemory = spuMemory;
            return this;
        }
        @CustomType.Setter
        public Builder spuPendingSession(Integer spuPendingSession) {
            if (spuPendingSession == null) {
              throw new MissingRequiredPropertyException("GetGatewayStatsDeviceGatewayStatSpu2Stat", "spuPendingSession");
            }
            this.spuPendingSession = spuPendingSession;
            return this;
        }
        @CustomType.Setter
        public Builder spuUptime(Integer spuUptime) {
            if (spuUptime == null) {
              throw new MissingRequiredPropertyException("GetGatewayStatsDeviceGatewayStatSpu2Stat", "spuUptime");
            }
            this.spuUptime = spuUptime;
            return this;
        }
        @CustomType.Setter
        public Builder spuValidSession(Integer spuValidSession) {
            if (spuValidSession == null) {
              throw new MissingRequiredPropertyException("GetGatewayStatsDeviceGatewayStatSpu2Stat", "spuValidSession");
            }
            this.spuValidSession = spuValidSession;
            return this;
        }
        public GetGatewayStatsDeviceGatewayStatSpu2Stat build() {
            final var _resultValue = new GetGatewayStatsDeviceGatewayStatSpu2Stat();
            _resultValue.spuCpu = spuCpu;
            _resultValue.spuCurrentSession = spuCurrentSession;
            _resultValue.spuMaxSession = spuMaxSession;
            _resultValue.spuMemory = spuMemory;
            _resultValue.spuPendingSession = spuPendingSession;
            _resultValue.spuUptime = spuUptime;
            _resultValue.spuValidSession = spuValidSession;
            return _resultValue;
        }
    }
}
