// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * This resource manages the Org WLAN Templates.
 *
 * A WLAN template is a collection of WLANs, tunneling policies, and wxlan policies. It is used to create and manage wlan configurations at an organizational level.\
 * WLAN templates allow for modular, scalable, and easy-to-manage configuration of ssids and their application to specific sites, site groups, or ap device profiles.\
 * They are valuable for automating configuration across multiple sites and profiles, making it easier to scale efficiently.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as junipermist from "@pulumi/juniper-mist";
 *
 * const wlantemplateOne = new junipermist.org.Wlantemplate("wlantemplate_one", {
 *     name: "wlantemplate_one",
 *     orgId: terraformTest.id,
 *     applies: {
 *         siteIds: [terraformSite.id],
 *     },
 * });
 * ```
 *
 * ## Import
 *
 * Using `pulumi import`, import `junipermist.org.Wlantemplate` with:
 * Org WLAN Template can be imported by specifying the orgId and the wlantemplateId
 *
 * ```sh
 * $ pulumi import junipermist:org/wlantemplate:Wlantemplate wlantemplate_one 17b46405-3a6d-4715-8bb4-6bb6d06f316a.d3c42998-9012-4859-9743-6b9bee475309
 * ```
 */
export class Wlantemplate extends pulumi.CustomResource {
    /**
     * Get an existing Wlantemplate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WlantemplateState, opts?: pulumi.CustomResourceOptions): Wlantemplate {
        return new Wlantemplate(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'junipermist:org/wlantemplate:Wlantemplate';

    /**
     * Returns true if the given object is an instance of Wlantemplate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Wlantemplate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Wlantemplate.__pulumiType;
    }

    /**
     * Organizations, sites, or site groups targeted by this WLAN template
     */
    declare public readonly applies: pulumi.Output<outputs.org.WlantemplateApplies>;
    /**
     * Device profile IDs that further limit where this WLAN template applies
     */
    declare public readonly deviceprofileIds: pulumi.Output<string[]>;
    /**
     * Sites or site groups excluded from this WLAN template even when included by the application scope
     */
    declare public readonly exceptions: pulumi.Output<outputs.org.WlantemplateExceptions>;
    /**
     * Whether to further filter by Device Profile
     */
    declare public readonly filterByDeviceprofile: pulumi.Output<boolean>;
    /**
     * Display name of the WLAN template
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Organization that owns this WLAN template
     */
    declare public readonly orgId: pulumi.Output<string>;

    /**
     * Create a Wlantemplate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WlantemplateArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WlantemplateArgs | WlantemplateState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WlantemplateState | undefined;
            resourceInputs["applies"] = state?.applies;
            resourceInputs["deviceprofileIds"] = state?.deviceprofileIds;
            resourceInputs["exceptions"] = state?.exceptions;
            resourceInputs["filterByDeviceprofile"] = state?.filterByDeviceprofile;
            resourceInputs["name"] = state?.name;
            resourceInputs["orgId"] = state?.orgId;
        } else {
            const args = argsOrState as WlantemplateArgs | undefined;
            if (args?.orgId === undefined && !opts.urn) {
                throw new Error("Missing required property 'orgId'");
            }
            resourceInputs["applies"] = args?.applies;
            resourceInputs["deviceprofileIds"] = args?.deviceprofileIds;
            resourceInputs["exceptions"] = args?.exceptions;
            resourceInputs["filterByDeviceprofile"] = args?.filterByDeviceprofile;
            resourceInputs["name"] = args?.name;
            resourceInputs["orgId"] = args?.orgId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Wlantemplate.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Wlantemplate resources.
 */
export interface WlantemplateState {
    /**
     * Organizations, sites, or site groups targeted by this WLAN template
     */
    applies?: pulumi.Input<inputs.org.WlantemplateApplies | undefined>;
    /**
     * Device profile IDs that further limit where this WLAN template applies
     */
    deviceprofileIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Sites or site groups excluded from this WLAN template even when included by the application scope
     */
    exceptions?: pulumi.Input<inputs.org.WlantemplateExceptions | undefined>;
    /**
     * Whether to further filter by Device Profile
     */
    filterByDeviceprofile?: pulumi.Input<boolean | undefined>;
    /**
     * Display name of the WLAN template
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Organization that owns this WLAN template
     */
    orgId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Wlantemplate resource.
 */
export interface WlantemplateArgs {
    /**
     * Organizations, sites, or site groups targeted by this WLAN template
     */
    applies?: pulumi.Input<inputs.org.WlantemplateApplies | undefined>;
    /**
     * Device profile IDs that further limit where this WLAN template applies
     */
    deviceprofileIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Sites or site groups excluded from this WLAN template even when included by the application scope
     */
    exceptions?: pulumi.Input<inputs.org.WlantemplateExceptions | undefined>;
    /**
     * Whether to further filter by Device Profile
     */
    filterByDeviceprofile?: pulumi.Input<boolean | undefined>;
    /**
     * Display name of the WLAN template
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Organization that owns this WLAN template
     */
    orgId: pulumi.Input<string>;
}
