// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.junipermist.site.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SettingIotproxyVisionlineArgs extends com.pulumi.resources.ResourceArgs {

    public static final SettingIotproxyVisionlineArgs Empty = new SettingIotproxyVisionlineArgs();

    /**
     * Access ID for the Visionline service
     * 
     */
    @Import(name="accessId")
    private @Nullable Output<String> accessId;

    /**
     * @return Access ID for the Visionline service
     * 
     */
    public Optional<Output<String>> accessId() {
        return Optional.ofNullable(this.accessId);
    }

    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * Hostname or IP of the Visionline collector
     * 
     */
    @Import(name="host")
    private @Nullable Output<String> host;

    /**
     * @return Hostname or IP of the Visionline collector
     * 
     */
    public Optional<Output<String>> host() {
        return Optional.ofNullable(this.host);
    }

    /**
     * Password for the Visionline service
     * 
     */
    @Import(name="password")
    private @Nullable Output<String> password;

    /**
     * @return Password for the Visionline service
     * 
     */
    public Optional<Output<String>> password() {
        return Optional.ofNullable(this.password);
    }

    /**
     * TCP port of the Visionline collector
     * 
     */
    @Import(name="port")
    private @Nullable Output<Integer> port;

    /**
     * @return TCP port of the Visionline collector
     * 
     */
    public Optional<Output<Integer>> port() {
        return Optional.ofNullable(this.port);
    }

    /**
     * Username for the Visionline service
     * 
     */
    @Import(name="username")
    private @Nullable Output<String> username;

    /**
     * @return Username for the Visionline service
     * 
     */
    public Optional<Output<String>> username() {
        return Optional.ofNullable(this.username);
    }

    private SettingIotproxyVisionlineArgs() {}

    private SettingIotproxyVisionlineArgs(SettingIotproxyVisionlineArgs $) {
        this.accessId = $.accessId;
        this.enabled = $.enabled;
        this.host = $.host;
        this.password = $.password;
        this.port = $.port;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SettingIotproxyVisionlineArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SettingIotproxyVisionlineArgs $;

        public Builder() {
            $ = new SettingIotproxyVisionlineArgs();
        }

        public Builder(SettingIotproxyVisionlineArgs defaults) {
            $ = new SettingIotproxyVisionlineArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accessId Access ID for the Visionline service
         * 
         * @return builder
         * 
         */
        public Builder accessId(@Nullable Output<String> accessId) {
            $.accessId = accessId;
            return this;
        }

        /**
         * @param accessId Access ID for the Visionline service
         * 
         * @return builder
         * 
         */
        public Builder accessId(String accessId) {
            return accessId(Output.of(accessId));
        }

        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param host Hostname or IP of the Visionline collector
         * 
         * @return builder
         * 
         */
        public Builder host(@Nullable Output<String> host) {
            $.host = host;
            return this;
        }

        /**
         * @param host Hostname or IP of the Visionline collector
         * 
         * @return builder
         * 
         */
        public Builder host(String host) {
            return host(Output.of(host));
        }

        /**
         * @param password Password for the Visionline service
         * 
         * @return builder
         * 
         */
        public Builder password(@Nullable Output<String> password) {
            $.password = password;
            return this;
        }

        /**
         * @param password Password for the Visionline service
         * 
         * @return builder
         * 
         */
        public Builder password(String password) {
            return password(Output.of(password));
        }

        /**
         * @param port TCP port of the Visionline collector
         * 
         * @return builder
         * 
         */
        public Builder port(@Nullable Output<Integer> port) {
            $.port = port;
            return this;
        }

        /**
         * @param port TCP port of the Visionline collector
         * 
         * @return builder
         * 
         */
        public Builder port(Integer port) {
            return port(Output.of(port));
        }

        /**
         * @param username Username for the Visionline service
         * 
         * @return builder
         * 
         */
        public Builder username(@Nullable Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username Username for the Visionline service
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public SettingIotproxyVisionlineArgs build() {
            return $;
        }
    }

}
