provider: junipermist
major-version: 0
makeTemplate: bridged
generate-nightly-test-workflow: true
providerDefaultBranch: main
upstream-provider-repo: terraform-provider-mist

esc:
  enabled: true
  environment: imports/github-secrets # No repo-specific secrets.

env:
  MIST_ORG_ID: ${{ secrets.MIST_ORG_ID}}
  MIST_API_TOKEN: ${{ secrets.MIST_API_TOKEN}}
  MIST_HOST: ${{ secrets.MIST_HOST}}
  MIST_CLAIM_CODE_1: ${{ secrets.MIST_CLAIM_CODE_1}}
  MIST_CLAIM_CODE_2: ${{ secrets.MIST_CLAIM_CODE_2}}

plugins:
  - name: std
    version: "1.6.2"
  - name: terraform
    version: "1.0.16"
    kind: converter

integrationTestProvider: true

# Use `pulumi convert` for translating examples from TF to Pulumi.
pulumiConvert: 1
registryDocs: true
