// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Org.Outputs
{

    [OutputType]
    public sealed class DeviceprofileGatewayNetwork
    {
        /// <summary>
        /// Whether to disallow Mist Devices in the network
        /// </summary>
        public readonly bool? DisallowMistServices;
        /// <summary>
        /// IPv4 gateway address for this network
        /// </summary>
        public readonly string? Gateway;
        /// <summary>
        /// IPv6 gateway address for this network
        /// </summary>
        public readonly string? Gateway6;
        /// <summary>
        /// Internal access settings for this network
        /// </summary>
        public readonly Outputs.DeviceprofileGatewayNetworkInternalAccess? InternalAccess;
        /// <summary>
        /// Direct internet access and NAT settings for this network
        /// </summary>
        public readonly Outputs.DeviceprofileGatewayNetworkInternetAccess? InternetAccess;
        /// <summary>
        /// Whether to allow clients in the network to talk to each other
        /// </summary>
        public readonly bool? Isolation;
        /// <summary>
        /// Settings for multicast routing on this network
        /// </summary>
        public readonly Outputs.DeviceprofileGatewayNetworkMulticast? Multicast;
        /// <summary>
        /// Display name of the organization network
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Other network names this network can route to, for example through BGP, OSPF or static routes
        /// </summary>
        public readonly ImmutableArray<string> RoutedForNetworks;
        /// <summary>
        /// IPv4 subnet CIDR for this network
        /// </summary>
        public readonly string Subnet;
        /// <summary>
        /// IPv6 subnet CIDR for this network
        /// </summary>
        public readonly string? Subnet6;
        /// <summary>
        /// Tenant address mappings associated with this network
        /// </summary>
        public readonly ImmutableDictionary<string, Outputs.DeviceprofileGatewayNetworkTenants>? Tenants;
        /// <summary>
        /// VLAN ID or variable associated with this network
        /// </summary>
        public readonly string? VlanId;
        /// <summary>
        /// VPN access settings keyed by VPN name for this network
        /// </summary>
        public readonly ImmutableDictionary<string, Outputs.DeviceprofileGatewayNetworkVpnAccess>? VpnAccess;

        [OutputConstructor]
        private DeviceprofileGatewayNetwork(
            bool? disallowMistServices,

            string? gateway,

            string? gateway6,

            Outputs.DeviceprofileGatewayNetworkInternalAccess? internalAccess,

            Outputs.DeviceprofileGatewayNetworkInternetAccess? internetAccess,

            bool? isolation,

            Outputs.DeviceprofileGatewayNetworkMulticast? multicast,

            string name,

            ImmutableArray<string> routedForNetworks,

            string subnet,

            string? subnet6,

            ImmutableDictionary<string, Outputs.DeviceprofileGatewayNetworkTenants>? tenants,

            string? vlanId,

            ImmutableDictionary<string, Outputs.DeviceprofileGatewayNetworkVpnAccess>? vpnAccess)
        {
            DisallowMistServices = disallowMistServices;
            Gateway = gateway;
            Gateway6 = gateway6;
            InternalAccess = internalAccess;
            InternetAccess = internetAccess;
            Isolation = isolation;
            Multicast = multicast;
            Name = name;
            RoutedForNetworks = routedForNetworks;
            Subnet = subnet;
            Subnet6 = subnet6;
            Tenants = tenants;
            VlanId = vlanId;
            VpnAccess = vpnAccess;
        }
    }
}
