// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Org.Outputs
{

    [OutputType]
    public sealed class DeviceprofileSwitchSnmpConfigClientList
    {
        /// <summary>
        /// Name of the SNMP client list
        /// </summary>
        public readonly string? ClientListName;
        /// <summary>
        /// SNMP client IP addresses or CIDR ranges allowed by this list
        /// </summary>
        public readonly ImmutableArray<string> Clients;

        [OutputConstructor]
        private DeviceprofileSwitchSnmpConfigClientList(
            string? clientListName,

            ImmutableArray<string> clients)
        {
            ClientListName = clientListName;
            Clients = clients;
        }
    }
}
