// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Org.Outputs
{

    [OutputType]
    public sealed class DeviceprofileApRadioConfig
    {
        public readonly bool? AllowRrmDisable;
        /// <summary>
        /// Antenna gain for 2.4G - for models with external antenna only
        /// </summary>
        public readonly int? AntGain24;
        /// <summary>
        /// Antenna gain for 5G - for models with external antenna only
        /// </summary>
        public readonly int? AntGain5;
        /// <summary>
        /// Antenna gain for 6G - for models with external antenna only
        /// </summary>
        public readonly int? AntGain6;
        /// <summary>
        /// enum: `1x1`, `2x2`, `3x3`, `4x4`, `Default`
        /// </summary>
        public readonly string? AntennaMode;
        /// <summary>
        /// Radio Band AP settings
        /// </summary>
        public readonly Outputs.DeviceprofileApRadioConfigBand24? Band24;
        /// <summary>
        /// enum: `24`, `5`, `6`, `Auto`
        /// </summary>
        public readonly string? Band24Usage;
        /// <summary>
        /// Radio Band AP settings
        /// </summary>
        public readonly Outputs.DeviceprofileApRadioConfigBand5? Band5;
        /// <summary>
        /// Radio Band AP settings
        /// </summary>
        public readonly Outputs.DeviceprofileApRadioConfigBand5On24Radio? Band5On24Radio;
        /// <summary>
        /// Radio Band AP settings
        /// </summary>
        public readonly Outputs.DeviceprofileApRadioConfigBand6? Band6;
        /// <summary>
        /// Let RRM control everything, only the `Channels` and `AntGain` will be honored (i.e. disabled/bandwidth/power/band_24_usage are all controlled by RRM)
        /// </summary>
        public readonly bool? FullAutomaticRrm;
        /// <summary>
        /// To make an outdoor operate indoor. For an outdoor-ap, some channels are disallowed by default, this allows the user to use it as an indoor-ap
        /// </summary>
        public readonly bool? IndoorUse;
        /// <summary>
        /// Whether scanning radio is enabled
        /// </summary>
        public readonly bool? ScanningEnabled;

        [OutputConstructor]
        private DeviceprofileApRadioConfig(
            bool? allowRrmDisable,

            int? antGain24,

            int? antGain5,

            int? antGain6,

            string? antennaMode,

            Outputs.DeviceprofileApRadioConfigBand24? band24,

            string? band24Usage,

            Outputs.DeviceprofileApRadioConfigBand5? band5,

            Outputs.DeviceprofileApRadioConfigBand5On24Radio? band5On24Radio,

            Outputs.DeviceprofileApRadioConfigBand6? band6,

            bool? fullAutomaticRrm,

            bool? indoorUse,

            bool? scanningEnabled)
        {
            AllowRrmDisable = allowRrmDisable;
            AntGain24 = antGain24;
            AntGain5 = antGain5;
            AntGain6 = antGain6;
            AntennaMode = antennaMode;
            Band24 = band24;
            Band24Usage = band24Usage;
            Band5 = band5;
            Band5On24Radio = band5On24Radio;
            Band6 = band6;
            FullAutomaticRrm = fullAutomaticRrm;
            IndoorUse = indoorUse;
            ScanningEnabled = scanningEnabled;
        }
    }
}
