// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Org.Outputs
{

    [OutputType]
    public sealed class MxclusterMistDas
    {
        /// <summary>
        /// Dynamic authorization clients allowed to send CoA or Disconnect-Message requests
        /// </summary>
        public readonly ImmutableArray<Outputs.MxclusterMistDasCoaServer> CoaServers;
        /// <summary>
        /// Whether cloud-assisted DAS is enabled for the Mist Edge cluster
        /// </summary>
        public readonly bool? Enabled;

        [OutputConstructor]
        private MxclusterMistDas(
            ImmutableArray<Outputs.MxclusterMistDasCoaServer> coaServers,

            bool? enabled)
        {
            CoaServers = coaServers;
            Enabled = enabled;
        }
    }
}
