// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Org.Outputs
{

    [OutputType]
    public sealed class NetworktemplateSnmpConfigV3ConfigTargetParameter
    {
        /// <summary>
        /// enum: `v1`, `v2c`, `v3`
        /// </summary>
        public readonly string? MessageProcessingModel;
        public readonly string? Name;
        /// <summary>
        /// refer to profile-name in notify_filter
        /// </summary>
        public readonly string? NotifyFilter;
        /// <summary>
        /// enum: `authentication`, `none`, `privacy`
        /// </summary>
        public readonly string? SecurityLevel;
        /// <summary>
        /// enum: `usm`, `v1`, `v2c`
        /// </summary>
        public readonly string? SecurityModel;
        /// <summary>
        /// refer to security_name in usm
        /// </summary>
        public readonly string? SecurityName;

        [OutputConstructor]
        private NetworktemplateSnmpConfigV3ConfigTargetParameter(
            string? messageProcessingModel,

            string? name,

            string? notifyFilter,

            string? securityLevel,

            string? securityModel,

            string? securityName)
        {
            MessageProcessingModel = messageProcessingModel;
            Name = name;
            NotifyFilter = notifyFilter;
            SecurityLevel = securityLevel;
            SecurityModel = securityModel;
            SecurityName = securityName;
        }
    }
}
