// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Org.Inputs
{

    public sealed class DeviceprofileGatewayTunnelProviderOptionsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// For jse-ipsec, this allows provisioning of adequate resource on JSE. Make sure adequate licenses are added
        /// </summary>
        [Input("jse")]
        public Input<Inputs.DeviceprofileGatewayTunnelProviderOptionsJseGetArgs>? Jse { get; set; }

        [Input("prisma")]
        public Input<Inputs.DeviceprofileGatewayTunnelProviderOptionsPrismaGetArgs>? Prisma { get; set; }

        /// <summary>
        /// For zscaler-ipsec and zscaler-gre
        /// </summary>
        [Input("zscaler")]
        public Input<Inputs.DeviceprofileGatewayTunnelProviderOptionsZscalerGetArgs>? Zscaler { get; set; }

        public DeviceprofileGatewayTunnelProviderOptionsGetArgs()
        {
        }
        public static new DeviceprofileGatewayTunnelProviderOptionsGetArgs Empty => new DeviceprofileGatewayTunnelProviderOptionsGetArgs();
    }
}
