// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Org.Inputs
{

    public sealed class NetworktemplateSnmpConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("clientLists")]
        private InputList<Inputs.NetworktemplateSnmpConfigClientListGetArgs>? _clientLists;

        /// <summary>
        /// SNMP client allowlists that can be referenced by communities
        /// </summary>
        public InputList<Inputs.NetworktemplateSnmpConfigClientListGetArgs> ClientLists
        {
            get => _clientLists ?? (_clientLists = new InputList<Inputs.NetworktemplateSnmpConfigClientListGetArgs>());
            set => _clientLists = value;
        }

        /// <summary>
        /// Administrative contact string advertised through SNMP
        /// </summary>
        [Input("contact")]
        public Input<string>? Contact { get; set; }

        /// <summary>
        /// Device description string advertised through SNMP
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Whether SNMP is enabled
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// SNMP engine ID used for SNMPv3
        /// </summary>
        [Input("engineId")]
        public Input<string>? EngineId { get; set; }

        /// <summary>
        /// Method used to derive the SNMP engine ID
        /// </summary>
        [Input("engineIdType")]
        public Input<string>? EngineIdType { get; set; }

        /// <summary>
        /// Physical location string advertised through SNMP
        /// </summary>
        [Input("location")]
        public Input<string>? Location { get; set; }

        /// <summary>
        /// System name advertised through SNMP
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Management network used for SNMP traffic
        /// </summary>
        [Input("network")]
        public Input<string>? Network { get; set; }

        [Input("trapGroups")]
        private InputList<Inputs.NetworktemplateSnmpConfigTrapGroupGetArgs>? _trapGroups;

        /// <summary>
        /// SNMP trap group definitions
        /// </summary>
        public InputList<Inputs.NetworktemplateSnmpConfigTrapGroupGetArgs> TrapGroups
        {
            get => _trapGroups ?? (_trapGroups = new InputList<Inputs.NetworktemplateSnmpConfigTrapGroupGetArgs>());
            set => _trapGroups = value;
        }

        [Input("v2cConfigs")]
        private InputList<Inputs.NetworktemplateSnmpConfigV2cConfigGetArgs>? _v2cConfigs;

        /// <summary>
        /// SNMPv2c community configuration entries for this SNMP profile
        /// </summary>
        public InputList<Inputs.NetworktemplateSnmpConfigV2cConfigGetArgs> V2cConfigs
        {
            get => _v2cConfigs ?? (_v2cConfigs = new InputList<Inputs.NetworktemplateSnmpConfigV2cConfigGetArgs>());
            set => _v2cConfigs = value;
        }

        /// <summary>
        /// SNMPv3 user, VACM, notify, and target configuration
        /// </summary>
        [Input("v3Config")]
        public Input<Inputs.NetworktemplateSnmpConfigV3ConfigGetArgs>? V3Config { get; set; }

        [Input("views")]
        private InputList<Inputs.NetworktemplateSnmpConfigViewGetArgs>? _views;

        /// <summary>
        /// SNMP MIB view definitions
        /// </summary>
        public InputList<Inputs.NetworktemplateSnmpConfigViewGetArgs> Views
        {
            get => _views ?? (_views = new InputList<Inputs.NetworktemplateSnmpConfigViewGetArgs>());
            set => _views = value;
        }

        public NetworktemplateSnmpConfigGetArgs()
        {
        }
        public static new NetworktemplateSnmpConfigGetArgs Empty => new NetworktemplateSnmpConfigGetArgs();
    }
}
