// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Org.Inputs
{

    public sealed class SettingJuniperAccountArgs : global::Pulumi.ResourceArgs
    {
        [Input("linkedBy")]
        public Input<string>? LinkedBy { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public SettingJuniperAccountArgs()
        {
        }
        public static new SettingJuniperAccountArgs Empty => new SettingJuniperAccountArgs();
    }
}
