// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Org.Inputs
{

    public sealed class WlanScheduleHoursGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Operating hour range for Friday
        /// </summary>
        [Input("fri")]
        public Input<string>? Fri { get; set; }

        /// <summary>
        /// Operating hour range for Monday
        /// </summary>
        [Input("mon")]
        public Input<string>? Mon { get; set; }

        /// <summary>
        /// Operating hour range for Saturday
        /// </summary>
        [Input("sat")]
        public Input<string>? Sat { get; set; }

        /// <summary>
        /// Operating hour range for Sunday
        /// </summary>
        [Input("sun")]
        public Input<string>? Sun { get; set; }

        /// <summary>
        /// Operating hour range for Thursday
        /// </summary>
        [Input("thu")]
        public Input<string>? Thu { get; set; }

        /// <summary>
        /// Operating hour range for Tuesday
        /// </summary>
        [Input("tue")]
        public Input<string>? Tue { get; set; }

        /// <summary>
        /// Operating hour range for Wednesday
        /// </summary>
        [Input("wed")]
        public Input<string>? Wed { get; set; }

        public WlanScheduleHoursGetArgs()
        {
        }
        public static new WlanScheduleHoursGetArgs Empty => new WlanScheduleHoursGetArgs();
    }
}
