// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Site.Inputs
{

    public sealed class SettingAutoUpgradeArgs : global::Pulumi.ResourceArgs
    {
        [Input("customVersions")]
        private InputMap<string>? _customVersions;

        /// <summary>
        /// Per-AP-model firmware versions or channels used for auto-upgrade
        /// </summary>
        public InputMap<string> CustomVersions
        {
            get => _customVersions ?? (_customVersions = new InputMap<string>());
            set => _customVersions = value;
        }

        /// <summary>
        /// Weekly AP auto-upgrade day for the maintenance window
        /// </summary>
        [Input("dayOfWeek")]
        public Input<string>? DayOfWeek { get; set; }

        /// <summary>
        /// Whether auto upgrade should happen (Note that Mist may auto-upgrade if the version is not supported)
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// `Any` / HH:MM (24-hour format), upgrade will happen within up to 1-hour from this time
        /// </summary>
        [Input("timeOfDay")]
        public Input<string>? TimeOfDay { get; set; }

        /// <summary>
        /// Firmware release channel or custom version used for AP auto-upgrade
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public SettingAutoUpgradeArgs()
        {
        }
        public static new SettingAutoUpgradeArgs Empty => new SettingAutoUpgradeArgs();
    }
}
