// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Device.Inputs
{

    public sealed class GatewayGatewayMgmtAppProbingGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("apps")]
        private InputList<string>? _apps;

        /// <summary>
        /// Predefined application keys to probe
        /// </summary>
        public InputList<string> Apps
        {
            get => _apps ?? (_apps = new InputList<string>());
            set => _apps = value;
        }

        [Input("customApps")]
        private InputList<Inputs.GatewayGatewayMgmtAppProbingCustomAppGetArgs>? _customApps;

        /// <summary>
        /// User-defined application probe definitions
        /// </summary>
        public InputList<Inputs.GatewayGatewayMgmtAppProbingCustomAppGetArgs> CustomApps
        {
            get => _customApps ?? (_customApps = new InputList<Inputs.GatewayGatewayMgmtAppProbingCustomAppGetArgs>());
            set => _customApps = value;
        }

        /// <summary>
        /// Whether gateway application probing is enabled
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        public GatewayGatewayMgmtAppProbingGetArgs()
        {
        }
        public static new GatewayGatewayMgmtAppProbingGetArgs Empty => new GatewayGatewayMgmtAppProbingGetArgs();
    }
}
