// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Device.Inputs
{

    public sealed class SwitchRemoteSyslogArchiveGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("files")]
        public Input<string>? Files { get; set; }

        [Input("size")]
        public Input<string>? Size { get; set; }

        public SwitchRemoteSyslogArchiveGetArgs()
        {
        }
        public static new SwitchRemoteSyslogArchiveGetArgs Empty => new SwitchRemoteSyslogArchiveGetArgs();
    }
}
