// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package site

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-junipermist/sdk/go/junipermist/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "junipermist:site/base:base":
		r = &Base{}
	case "junipermist:site/networktemplate:Networktemplate":
		r = &Networktemplate{}
	case "junipermist:site/psk:Psk":
		r = &Psk{}
	case "junipermist:site/setting:Setting":
		r = &Setting{}
	case "junipermist:site/webhook:Webhook":
		r = &Webhook{}
	case "junipermist:site/wlan:Wlan":
		r = &Wlan{}
	case "junipermist:site/wlanPortalTemplate:WlanPortalTemplate":
		r = &WlanPortalTemplate{}
	case "junipermist:site/wxrule:Wxrule":
		r = &Wxrule{}
	case "junipermist:site/wxtag:Wxtag":
		r = &Wxtag{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"junipermist",
		"site/base",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"junipermist",
		"site/networktemplate",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"junipermist",
		"site/psk",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"junipermist",
		"site/setting",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"junipermist",
		"site/webhook",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"junipermist",
		"site/wlan",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"junipermist",
		"site/wlanPortalTemplate",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"junipermist",
		"site/wxrule",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"junipermist",
		"site/wxtag",
		&module{version},
	)
}
