// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.junipermist.device.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SwitchStpConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final SwitchStpConfigArgs Empty = new SwitchStpConfigArgs();

    /**
     * enum: `rstp`, `vstp`
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return enum: `rstp`, `vstp`
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private SwitchStpConfigArgs() {}

    private SwitchStpConfigArgs(SwitchStpConfigArgs $) {
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SwitchStpConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SwitchStpConfigArgs $;

        public Builder() {
            $ = new SwitchStpConfigArgs();
        }

        public Builder(SwitchStpConfigArgs defaults) {
            $ = new SwitchStpConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param type enum: `rstp`, `vstp`
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type enum: `rstp`, `vstp`
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public SwitchStpConfigArgs build() {
            return $;
        }
    }

}
