// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.junipermist.device.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.junipermist.device.inputs.SwitchRoutingPoliciesTermActionsArgs;
import com.pulumi.junipermist.device.inputs.SwitchRoutingPoliciesTermMatchingArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SwitchRoutingPoliciesTermArgs extends com.pulumi.resources.ResourceArgs {

    public static final SwitchRoutingPoliciesTermArgs Empty = new SwitchRoutingPoliciesTermArgs();

    /**
     * When used as import policy
     * 
     */
    @Import(name="actions")
    private @Nullable Output<SwitchRoutingPoliciesTermActionsArgs> actions;

    /**
     * @return When used as import policy
     * 
     */
    public Optional<Output<SwitchRoutingPoliciesTermActionsArgs>> actions() {
        return Optional.ofNullable(this.actions);
    }

    /**
     * zero or more criteria/filter can be specified to match the term, all criteria have to be met
     * 
     */
    @Import(name="matching")
    private @Nullable Output<SwitchRoutingPoliciesTermMatchingArgs> matching;

    /**
     * @return zero or more criteria/filter can be specified to match the term, all criteria have to be met
     * 
     */
    public Optional<Output<SwitchRoutingPoliciesTermMatchingArgs>> matching() {
        return Optional.ofNullable(this.matching);
    }

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    private SwitchRoutingPoliciesTermArgs() {}

    private SwitchRoutingPoliciesTermArgs(SwitchRoutingPoliciesTermArgs $) {
        this.actions = $.actions;
        this.matching = $.matching;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SwitchRoutingPoliciesTermArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SwitchRoutingPoliciesTermArgs $;

        public Builder() {
            $ = new SwitchRoutingPoliciesTermArgs();
        }

        public Builder(SwitchRoutingPoliciesTermArgs defaults) {
            $ = new SwitchRoutingPoliciesTermArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param actions When used as import policy
         * 
         * @return builder
         * 
         */
        public Builder actions(@Nullable Output<SwitchRoutingPoliciesTermActionsArgs> actions) {
            $.actions = actions;
            return this;
        }

        /**
         * @param actions When used as import policy
         * 
         * @return builder
         * 
         */
        public Builder actions(SwitchRoutingPoliciesTermActionsArgs actions) {
            return actions(Output.of(actions));
        }

        /**
         * @param matching zero or more criteria/filter can be specified to match the term, all criteria have to be met
         * 
         * @return builder
         * 
         */
        public Builder matching(@Nullable Output<SwitchRoutingPoliciesTermMatchingArgs> matching) {
            $.matching = matching;
            return this;
        }

        /**
         * @param matching zero or more criteria/filter can be specified to match the term, all criteria have to be met
         * 
         * @return builder
         * 
         */
        public Builder matching(SwitchRoutingPoliciesTermMatchingArgs matching) {
            return matching(Output.of(matching));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public SwitchRoutingPoliciesTermArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("SwitchRoutingPoliciesTermArgs", "name");
            }
            return $;
        }
    }

}
