// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.junipermist.device.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SwitchOspfConfigAreasArgs extends com.pulumi.resources.ResourceArgs {

    public static final SwitchOspfConfigAreasArgs Empty = new SwitchOspfConfigAreasArgs();

    /**
     * Disable OSPF summary routes for this area
     * 
     */
    @Import(name="noSummary")
    private @Nullable Output<Boolean> noSummary;

    /**
     * @return Disable OSPF summary routes for this area
     * 
     */
    public Optional<Output<Boolean>> noSummary() {
        return Optional.ofNullable(this.noSummary);
    }

    private SwitchOspfConfigAreasArgs() {}

    private SwitchOspfConfigAreasArgs(SwitchOspfConfigAreasArgs $) {
        this.noSummary = $.noSummary;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SwitchOspfConfigAreasArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SwitchOspfConfigAreasArgs $;

        public Builder() {
            $ = new SwitchOspfConfigAreasArgs();
        }

        public Builder(SwitchOspfConfigAreasArgs defaults) {
            $ = new SwitchOspfConfigAreasArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param noSummary Disable OSPF summary routes for this area
         * 
         * @return builder
         * 
         */
        public Builder noSummary(@Nullable Output<Boolean> noSummary) {
            $.noSummary = noSummary;
            return this;
        }

        /**
         * @param noSummary Disable OSPF summary routes for this area
         * 
         * @return builder
         * 
         */
        public Builder noSummary(Boolean noSummary) {
            return noSummary(Output.of(noSummary));
        }

        public SwitchOspfConfigAreasArgs build() {
            return $;
        }
    }

}
