// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.junipermist.org.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.junipermist.org.inputs.DeviceprofileGatewayOobIpConfigNode1Args;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DeviceprofileGatewayOobIpConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final DeviceprofileGatewayOobIpConfigArgs Empty = new DeviceprofileGatewayOobIpConfigArgs();

    /**
     * Default gateway for the out-of-band management interface when `type`==`static`
     * 
     */
    @Import(name="gateway")
    private @Nullable Output<String> gateway;

    /**
     * @return Default gateway for the out-of-band management interface when `type`==`static`
     * 
     */
    public Optional<Output<String>> gateway() {
        return Optional.ofNullable(this.gateway);
    }

    /**
     * Static IPv4 address for the out-of-band management interface when `type`==`static`
     * 
     */
    @Import(name="ip")
    private @Nullable Output<String> ip;

    /**
     * @return Static IPv4 address for the out-of-band management interface when `type`==`static`
     * 
     */
    public Optional<Output<String>> ip() {
        return Optional.ofNullable(this.ip);
    }

    /**
     * IPv4 netmask or prefix length for the out-of-band management interface when `type`==`static`
     * 
     */
    @Import(name="netmask")
    private @Nullable Output<String> netmask;

    /**
     * @return IPv4 netmask or prefix length for the out-of-band management interface when `type`==`static`
     * 
     */
    public Optional<Output<String>> netmask() {
        return Optional.ofNullable(this.netmask);
    }

    /**
     * Out-of-band management IP configuration override for node1 in an HA cluster
     * 
     */
    @Import(name="node1")
    private @Nullable Output<DeviceprofileGatewayOobIpConfigNode1Args> node1;

    /**
     * @return Out-of-band management IP configuration override for node1 in an HA cluster
     * 
     */
    public Optional<Output<DeviceprofileGatewayOobIpConfigNode1Args>> node1() {
        return Optional.ofNullable(this.node1);
    }

    /**
     * IP assignment mode for the out-of-band management interface
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return IP assignment mode for the out-of-band management interface
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    /**
     * If supported on the platform. If enabled, DNS will be using this routing-instance, too
     * 
     */
    @Import(name="useMgmtVrf")
    private @Nullable Output<Boolean> useMgmtVrf;

    /**
     * @return If supported on the platform. If enabled, DNS will be using this routing-instance, too
     * 
     */
    public Optional<Output<Boolean>> useMgmtVrf() {
        return Optional.ofNullable(this.useMgmtVrf);
    }

    /**
     * For host-out traffic (NTP/TACPLUS/RADIUS/SYSLOG/SNMP), if alternative source network/ip is desired
     * 
     */
    @Import(name="useMgmtVrfForHostOut")
    private @Nullable Output<Boolean> useMgmtVrfForHostOut;

    /**
     * @return For host-out traffic (NTP/TACPLUS/RADIUS/SYSLOG/SNMP), if alternative source network/ip is desired
     * 
     */
    public Optional<Output<Boolean>> useMgmtVrfForHostOut() {
        return Optional.ofNullable(this.useMgmtVrfForHostOut);
    }

    /**
     * VLAN ID used for out-of-band management traffic
     * 
     */
    @Import(name="vlanId")
    private @Nullable Output<String> vlanId;

    /**
     * @return VLAN ID used for out-of-band management traffic
     * 
     */
    public Optional<Output<String>> vlanId() {
        return Optional.ofNullable(this.vlanId);
    }

    private DeviceprofileGatewayOobIpConfigArgs() {}

    private DeviceprofileGatewayOobIpConfigArgs(DeviceprofileGatewayOobIpConfigArgs $) {
        this.gateway = $.gateway;
        this.ip = $.ip;
        this.netmask = $.netmask;
        this.node1 = $.node1;
        this.type = $.type;
        this.useMgmtVrf = $.useMgmtVrf;
        this.useMgmtVrfForHostOut = $.useMgmtVrfForHostOut;
        this.vlanId = $.vlanId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DeviceprofileGatewayOobIpConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DeviceprofileGatewayOobIpConfigArgs $;

        public Builder() {
            $ = new DeviceprofileGatewayOobIpConfigArgs();
        }

        public Builder(DeviceprofileGatewayOobIpConfigArgs defaults) {
            $ = new DeviceprofileGatewayOobIpConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param gateway Default gateway for the out-of-band management interface when `type`==`static`
         * 
         * @return builder
         * 
         */
        public Builder gateway(@Nullable Output<String> gateway) {
            $.gateway = gateway;
            return this;
        }

        /**
         * @param gateway Default gateway for the out-of-band management interface when `type`==`static`
         * 
         * @return builder
         * 
         */
        public Builder gateway(String gateway) {
            return gateway(Output.of(gateway));
        }

        /**
         * @param ip Static IPv4 address for the out-of-band management interface when `type`==`static`
         * 
         * @return builder
         * 
         */
        public Builder ip(@Nullable Output<String> ip) {
            $.ip = ip;
            return this;
        }

        /**
         * @param ip Static IPv4 address for the out-of-band management interface when `type`==`static`
         * 
         * @return builder
         * 
         */
        public Builder ip(String ip) {
            return ip(Output.of(ip));
        }

        /**
         * @param netmask IPv4 netmask or prefix length for the out-of-band management interface when `type`==`static`
         * 
         * @return builder
         * 
         */
        public Builder netmask(@Nullable Output<String> netmask) {
            $.netmask = netmask;
            return this;
        }

        /**
         * @param netmask IPv4 netmask or prefix length for the out-of-band management interface when `type`==`static`
         * 
         * @return builder
         * 
         */
        public Builder netmask(String netmask) {
            return netmask(Output.of(netmask));
        }

        /**
         * @param node1 Out-of-band management IP configuration override for node1 in an HA cluster
         * 
         * @return builder
         * 
         */
        public Builder node1(@Nullable Output<DeviceprofileGatewayOobIpConfigNode1Args> node1) {
            $.node1 = node1;
            return this;
        }

        /**
         * @param node1 Out-of-band management IP configuration override for node1 in an HA cluster
         * 
         * @return builder
         * 
         */
        public Builder node1(DeviceprofileGatewayOobIpConfigNode1Args node1) {
            return node1(Output.of(node1));
        }

        /**
         * @param type IP assignment mode for the out-of-band management interface
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type IP assignment mode for the out-of-band management interface
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        /**
         * @param useMgmtVrf If supported on the platform. If enabled, DNS will be using this routing-instance, too
         * 
         * @return builder
         * 
         */
        public Builder useMgmtVrf(@Nullable Output<Boolean> useMgmtVrf) {
            $.useMgmtVrf = useMgmtVrf;
            return this;
        }

        /**
         * @param useMgmtVrf If supported on the platform. If enabled, DNS will be using this routing-instance, too
         * 
         * @return builder
         * 
         */
        public Builder useMgmtVrf(Boolean useMgmtVrf) {
            return useMgmtVrf(Output.of(useMgmtVrf));
        }

        /**
         * @param useMgmtVrfForHostOut For host-out traffic (NTP/TACPLUS/RADIUS/SYSLOG/SNMP), if alternative source network/ip is desired
         * 
         * @return builder
         * 
         */
        public Builder useMgmtVrfForHostOut(@Nullable Output<Boolean> useMgmtVrfForHostOut) {
            $.useMgmtVrfForHostOut = useMgmtVrfForHostOut;
            return this;
        }

        /**
         * @param useMgmtVrfForHostOut For host-out traffic (NTP/TACPLUS/RADIUS/SYSLOG/SNMP), if alternative source network/ip is desired
         * 
         * @return builder
         * 
         */
        public Builder useMgmtVrfForHostOut(Boolean useMgmtVrfForHostOut) {
            return useMgmtVrfForHostOut(Output.of(useMgmtVrfForHostOut));
        }

        /**
         * @param vlanId VLAN ID used for out-of-band management traffic
         * 
         * @return builder
         * 
         */
        public Builder vlanId(@Nullable Output<String> vlanId) {
            $.vlanId = vlanId;
            return this;
        }

        /**
         * @param vlanId VLAN ID used for out-of-band management traffic
         * 
         * @return builder
         * 
         */
        public Builder vlanId(String vlanId) {
            return vlanId(Output.of(vlanId));
        }

        public DeviceprofileGatewayOobIpConfigArgs build() {
            return $;
        }
    }

}
