// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.junipermist.org.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.junipermist.org.inputs.DeviceprofileSwitchRemoteSyslogConsoleContentArgs;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DeviceprofileSwitchRemoteSyslogConsoleArgs extends com.pulumi.resources.ResourceArgs {

    public static final DeviceprofileSwitchRemoteSyslogConsoleArgs Empty = new DeviceprofileSwitchRemoteSyslogConsoleArgs();

    /**
     * Syslog facilities and severities forwarded from console logs
     * 
     */
    @Import(name="contents")
    private @Nullable Output<List<DeviceprofileSwitchRemoteSyslogConsoleContentArgs>> contents;

    /**
     * @return Syslog facilities and severities forwarded from console logs
     * 
     */
    public Optional<Output<List<DeviceprofileSwitchRemoteSyslogConsoleContentArgs>>> contents() {
        return Optional.ofNullable(this.contents);
    }

    private DeviceprofileSwitchRemoteSyslogConsoleArgs() {}

    private DeviceprofileSwitchRemoteSyslogConsoleArgs(DeviceprofileSwitchRemoteSyslogConsoleArgs $) {
        this.contents = $.contents;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DeviceprofileSwitchRemoteSyslogConsoleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DeviceprofileSwitchRemoteSyslogConsoleArgs $;

        public Builder() {
            $ = new DeviceprofileSwitchRemoteSyslogConsoleArgs();
        }

        public Builder(DeviceprofileSwitchRemoteSyslogConsoleArgs defaults) {
            $ = new DeviceprofileSwitchRemoteSyslogConsoleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param contents Syslog facilities and severities forwarded from console logs
         * 
         * @return builder
         * 
         */
        public Builder contents(@Nullable Output<List<DeviceprofileSwitchRemoteSyslogConsoleContentArgs>> contents) {
            $.contents = contents;
            return this;
        }

        /**
         * @param contents Syslog facilities and severities forwarded from console logs
         * 
         * @return builder
         * 
         */
        public Builder contents(List<DeviceprofileSwitchRemoteSyslogConsoleContentArgs> contents) {
            return contents(Output.of(contents));
        }

        /**
         * @param contents Syslog facilities and severities forwarded from console logs
         * 
         * @return builder
         * 
         */
        public Builder contents(DeviceprofileSwitchRemoteSyslogConsoleContentArgs... contents) {
            return contents(List.of(contents));
        }

        public DeviceprofileSwitchRemoteSyslogConsoleArgs build() {
            return $;
        }
    }

}
