// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.junipermist.org.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DeviceprofileSwitchSnmpConfigViewArgs extends com.pulumi.resources.ResourceArgs {

    public static final DeviceprofileSwitchSnmpConfigViewArgs Empty = new DeviceprofileSwitchSnmpConfigViewArgs();

    /**
     * Whether the root OID is included in this SNMP view
     * 
     */
    @Import(name="include")
    private @Nullable Output<Boolean> include;

    /**
     * @return Whether the root OID is included in this SNMP view
     * 
     */
    public Optional<Output<Boolean>> include() {
        return Optional.ofNullable(this.include);
    }

    /**
     * Root OID for this SNMP view
     * 
     */
    @Import(name="oid")
    private @Nullable Output<String> oid;

    /**
     * @return Root OID for this SNMP view
     * 
     */
    public Optional<Output<String>> oid() {
        return Optional.ofNullable(this.oid);
    }

    /**
     * Name of the SNMP MIB view definition
     * 
     */
    @Import(name="viewName")
    private @Nullable Output<String> viewName;

    /**
     * @return Name of the SNMP MIB view definition
     * 
     */
    public Optional<Output<String>> viewName() {
        return Optional.ofNullable(this.viewName);
    }

    private DeviceprofileSwitchSnmpConfigViewArgs() {}

    private DeviceprofileSwitchSnmpConfigViewArgs(DeviceprofileSwitchSnmpConfigViewArgs $) {
        this.include = $.include;
        this.oid = $.oid;
        this.viewName = $.viewName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DeviceprofileSwitchSnmpConfigViewArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DeviceprofileSwitchSnmpConfigViewArgs $;

        public Builder() {
            $ = new DeviceprofileSwitchSnmpConfigViewArgs();
        }

        public Builder(DeviceprofileSwitchSnmpConfigViewArgs defaults) {
            $ = new DeviceprofileSwitchSnmpConfigViewArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param include Whether the root OID is included in this SNMP view
         * 
         * @return builder
         * 
         */
        public Builder include(@Nullable Output<Boolean> include) {
            $.include = include;
            return this;
        }

        /**
         * @param include Whether the root OID is included in this SNMP view
         * 
         * @return builder
         * 
         */
        public Builder include(Boolean include) {
            return include(Output.of(include));
        }

        /**
         * @param oid Root OID for this SNMP view
         * 
         * @return builder
         * 
         */
        public Builder oid(@Nullable Output<String> oid) {
            $.oid = oid;
            return this;
        }

        /**
         * @param oid Root OID for this SNMP view
         * 
         * @return builder
         * 
         */
        public Builder oid(String oid) {
            return oid(Output.of(oid));
        }

        /**
         * @param viewName Name of the SNMP MIB view definition
         * 
         * @return builder
         * 
         */
        public Builder viewName(@Nullable Output<String> viewName) {
            $.viewName = viewName;
            return this;
        }

        /**
         * @param viewName Name of the SNMP MIB view definition
         * 
         * @return builder
         * 
         */
        public Builder viewName(String viewName) {
            return viewName(Output.of(viewName));
        }

        public DeviceprofileSwitchSnmpConfigViewArgs build() {
            return $;
        }
    }

}
