// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.junipermist.org.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.junipermist.org.inputs.GatewaytemplatePathPreferencesPathArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GatewaytemplatePathPreferencesArgs extends com.pulumi.resources.ResourceArgs {

    public static final GatewaytemplatePathPreferencesArgs Empty = new GatewaytemplatePathPreferencesArgs();

    @Import(name="paths")
    private @Nullable Output<List<GatewaytemplatePathPreferencesPathArgs>> paths;

    public Optional<Output<List<GatewaytemplatePathPreferencesPathArgs>>> paths() {
        return Optional.ofNullable(this.paths);
    }

    /**
     * enum: `ecmp`, `ordered`, `weighted`
     * 
     */
    @Import(name="strategy")
    private @Nullable Output<String> strategy;

    /**
     * @return enum: `ecmp`, `ordered`, `weighted`
     * 
     */
    public Optional<Output<String>> strategy() {
        return Optional.ofNullable(this.strategy);
    }

    private GatewaytemplatePathPreferencesArgs() {}

    private GatewaytemplatePathPreferencesArgs(GatewaytemplatePathPreferencesArgs $) {
        this.paths = $.paths;
        this.strategy = $.strategy;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GatewaytemplatePathPreferencesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GatewaytemplatePathPreferencesArgs $;

        public Builder() {
            $ = new GatewaytemplatePathPreferencesArgs();
        }

        public Builder(GatewaytemplatePathPreferencesArgs defaults) {
            $ = new GatewaytemplatePathPreferencesArgs(Objects.requireNonNull(defaults));
        }

        public Builder paths(@Nullable Output<List<GatewaytemplatePathPreferencesPathArgs>> paths) {
            $.paths = paths;
            return this;
        }

        public Builder paths(List<GatewaytemplatePathPreferencesPathArgs> paths) {
            return paths(Output.of(paths));
        }

        public Builder paths(GatewaytemplatePathPreferencesPathArgs... paths) {
            return paths(List.of(paths));
        }

        /**
         * @param strategy enum: `ecmp`, `ordered`, `weighted`
         * 
         * @return builder
         * 
         */
        public Builder strategy(@Nullable Output<String> strategy) {
            $.strategy = strategy;
            return this;
        }

        /**
         * @param strategy enum: `ecmp`, `ordered`, `weighted`
         * 
         * @return builder
         * 
         */
        public Builder strategy(String strategy) {
            return strategy(Output.of(strategy));
        }

        public GatewaytemplatePathPreferencesArgs build() {
            return $;
        }
    }

}
