// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.junipermist.org.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SettingJuniperAccountArgs extends com.pulumi.resources.ResourceArgs {

    public static final SettingJuniperAccountArgs Empty = new SettingJuniperAccountArgs();

    @Import(name="linkedBy")
    private @Nullable Output<String> linkedBy;

    public Optional<Output<String>> linkedBy() {
        return Optional.ofNullable(this.linkedBy);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private SettingJuniperAccountArgs() {}

    private SettingJuniperAccountArgs(SettingJuniperAccountArgs $) {
        this.linkedBy = $.linkedBy;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SettingJuniperAccountArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SettingJuniperAccountArgs $;

        public Builder() {
            $ = new SettingJuniperAccountArgs();
        }

        public Builder(SettingJuniperAccountArgs defaults) {
            $ = new SettingJuniperAccountArgs(Objects.requireNonNull(defaults));
        }

        public Builder linkedBy(@Nullable Output<String> linkedBy) {
            $.linkedBy = linkedBy;
            return this;
        }

        public Builder linkedBy(String linkedBy) {
            return linkedBy(Output.of(linkedBy));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public SettingJuniperAccountArgs build() {
            return $;
        }
    }

}
