// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.junipermist.org.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SettingCradlepointArgs extends com.pulumi.resources.ResourceArgs {

    public static final SettingCradlepointArgs Empty = new SettingCradlepointArgs();

    @Import(name="cpApiId")
    private @Nullable Output<String> cpApiId;

    public Optional<Output<String>> cpApiId() {
        return Optional.ofNullable(this.cpApiId);
    }

    @Import(name="cpApiKey")
    private @Nullable Output<String> cpApiKey;

    public Optional<Output<String>> cpApiKey() {
        return Optional.ofNullable(this.cpApiKey);
    }

    @Import(name="ecmApiId")
    private @Nullable Output<String> ecmApiId;

    public Optional<Output<String>> ecmApiId() {
        return Optional.ofNullable(this.ecmApiId);
    }

    @Import(name="ecmApiKey")
    private @Nullable Output<String> ecmApiKey;

    public Optional<Output<String>> ecmApiKey() {
        return Optional.ofNullable(this.ecmApiKey);
    }

    @Import(name="enableLldp")
    private @Nullable Output<Boolean> enableLldp;

    public Optional<Output<Boolean>> enableLldp() {
        return Optional.ofNullable(this.enableLldp);
    }

    private SettingCradlepointArgs() {}

    private SettingCradlepointArgs(SettingCradlepointArgs $) {
        this.cpApiId = $.cpApiId;
        this.cpApiKey = $.cpApiKey;
        this.ecmApiId = $.ecmApiId;
        this.ecmApiKey = $.ecmApiKey;
        this.enableLldp = $.enableLldp;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SettingCradlepointArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SettingCradlepointArgs $;

        public Builder() {
            $ = new SettingCradlepointArgs();
        }

        public Builder(SettingCradlepointArgs defaults) {
            $ = new SettingCradlepointArgs(Objects.requireNonNull(defaults));
        }

        public Builder cpApiId(@Nullable Output<String> cpApiId) {
            $.cpApiId = cpApiId;
            return this;
        }

        public Builder cpApiId(String cpApiId) {
            return cpApiId(Output.of(cpApiId));
        }

        public Builder cpApiKey(@Nullable Output<String> cpApiKey) {
            $.cpApiKey = cpApiKey;
            return this;
        }

        public Builder cpApiKey(String cpApiKey) {
            return cpApiKey(Output.of(cpApiKey));
        }

        public Builder ecmApiId(@Nullable Output<String> ecmApiId) {
            $.ecmApiId = ecmApiId;
            return this;
        }

        public Builder ecmApiId(String ecmApiId) {
            return ecmApiId(Output.of(ecmApiId));
        }

        public Builder ecmApiKey(@Nullable Output<String> ecmApiKey) {
            $.ecmApiKey = ecmApiKey;
            return this;
        }

        public Builder ecmApiKey(String ecmApiKey) {
            return ecmApiKey(Output.of(ecmApiKey));
        }

        public Builder enableLldp(@Nullable Output<Boolean> enableLldp) {
            $.enableLldp = enableLldp;
            return this;
        }

        public Builder enableLldp(Boolean enableLldp) {
            return enableLldp(Output.of(enableLldp));
        }

        public SettingCradlepointArgs build() {
            return $;
        }
    }

}
