// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Site.Outputs
{

    [OutputType]
    public sealed class SettingGatewayMgmtAppProbingCustomApp
    {
        /// <summary>
        /// if `protocol`==`icmp`
        /// </summary>
        public readonly string? Address;
        public readonly string? AppType;
        /// <summary>
        /// if `protocol`==`http`
        /// </summary>
        public readonly ImmutableArray<string> Hostnames;
        public readonly string? Name;
        public readonly string? Network;
        /// <summary>
        /// enum: `http`, `icmp`
        /// </summary>
        public readonly string? Protocol;
        /// <summary>
        /// if `protocol`==`http`
        /// </summary>
        public readonly string? Url;
        public readonly string? Vrf;

        [OutputConstructor]
        private SettingGatewayMgmtAppProbingCustomApp(
            string? address,

            string? appType,

            ImmutableArray<string> hostnames,

            string? name,

            string? network,

            string? protocol,

            string? url,

            string? vrf)
        {
            Address = address;
            AppType = appType;
            Hostnames = hostnames;
            Name = name;
            Network = network;
            Protocol = protocol;
            Url = url;
            Vrf = vrf;
        }
    }
}
