// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.junipermist.site.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class WlanMistNac {
    /**
     * @return when enabled:
     *   * `auth_servers` is ignored
     *   * `acct_servers` is ignored
     *   * `auth_servers_*` are ignored
     *   * `coa_servers` is ignored
     *   * `radsec` is ignored
     *   * `coa_enabled` is assumed&#39;
     * 
     */
    private @Nullable Boolean enabled;

    private WlanMistNac() {}
    /**
     * @return when enabled:
     *   * `auth_servers` is ignored
     *   * `acct_servers` is ignored
     *   * `auth_servers_*` are ignored
     *   * `coa_servers` is ignored
     *   * `radsec` is ignored
     *   * `coa_enabled` is assumed&#39;
     * 
     */
    public Optional<Boolean> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(WlanMistNac defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean enabled;
        public Builder() {}
        public Builder(WlanMistNac defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enabled = defaults.enabled;
        }

        @CustomType.Setter
        public Builder enabled(@Nullable Boolean enabled) {

            this.enabled = enabled;
            return this;
        }
        public WlanMistNac build() {
            final var _resultValue = new WlanMistNac();
            _resultValue.enabled = enabled;
            return _resultValue;
        }
    }
}
