// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Org
{
    /// <summary>
    /// This resource manages Mist Tunnels in the Mist Organization.
    /// 
    /// A Mist Tunnel (MxTunnel) defines tunneling configuration used to carry AP user VLANs to Mist Edge clusters.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using JuniperMist = Pulumi.JuniperMist;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var mxtunnelOne = new JuniperMist.Org.Mxtunnel("mxtunnel_one", new()
    ///     {
    ///         OrgId = terraformTest.Id,
    ///         Name = "mxtunnel_one",
    ///         Protocol = "udp",
    ///         HelloInterval = 60,
    ///         HelloRetries = 7,
    ///         Mtu = 0,
    ///         VlanIds = new[]
    ///         {
    ///             10,
    ///             20,
    ///             30,
    ///         },
    ///         MxclusterIds = new[]
    ///         {
    ///             mxclusterOne.Id,
    ///         },
    ///         AutoPreemption = new JuniperMist.Org.Inputs.MxtunnelAutoPreemptionArgs
    ///         {
    ///             Enabled = true,
    ///             DayOfWeek = "mon",
    ///             TimeOfDay = "02:00",
    ///         },
    ///         Ipsec = new JuniperMist.Org.Inputs.MxtunnelIpsecArgs
    ///         {
    ///             Enabled = true,
    ///             SplitTunnel = true,
    ///             UseMxedge = true,
    ///             DnsServers = new[]
    ///             {
    ///                 "8.8.8.8",
    ///                 "8.8.4.4",
    ///             },
    ///             DnsSuffixes = new[]
    ///             {
    ///                 "corp.example.com",
    ///             },
    ///             ExtraRoutes = new[]
    ///             {
    ///                 new JuniperMist.Org.Inputs.MxtunnelIpsecExtraRouteArgs
    ///                 {
    ///                     Dest = "10.0.0.0/8",
    ///                     NextHop = "192.168.1.1",
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Using `pulumi import`, import `junipermist.org.Mxtunnel` with:
    /// Mist Org MxTunnel can be imported by specifying the OrgId and the MxtunnelId
    /// 
    /// ```sh
    /// $ pulumi import junipermist:org/mxtunnel:Mxtunnel mxtunnel_one 17f90707-aebe-4274-af42-f42952a665a3.d3c42998-9012-4859-9743-6a9f30d68218
    /// ```
    /// </summary>
    [JuniperMistResourceType("junipermist:org/mxtunnel:Mxtunnel")]
    public partial class Mxtunnel : global::Pulumi.CustomResource
    {
        /// <summary>
        /// IDs of anchor Mist Tunnels used for edge-to-edge tunnel formation
        /// </summary>
        [Output("anchorMxtunnelIds")]
        public Output<ImmutableArray<string>> AnchorMxtunnelIds { get; private set; } = null!;

        /// <summary>
        /// Preemption behavior for restoring preferred tunnel peers after failover
        /// </summary>
        [Output("autoPreemption")]
        public Output<Outputs.MxtunnelAutoPreemption?> AutoPreemption { get; private set; } = null!;

        /// <summary>
        /// In seconds, used as heartbeat to detect if a tunnel is alive. AP will try another peer after missing N hellos specified by `HelloRetries`.
        /// </summary>
        [Output("helloInterval")]
        public Output<int?> HelloInterval { get; private set; } = null!;

        /// <summary>
        /// Number of missed hello heartbeats before an AP tries another tunnel peer
        /// </summary>
        [Output("helloRetries")]
        public Output<int?> HelloRetries { get; private set; } = null!;

        /// <summary>
        /// Security settings for IPsec support on this Mist Tunnel
        /// </summary>
        [Output("ipsec")]
        public Output<Outputs.MxtunnelIpsec?> Ipsec { get; private set; } = null!;

        /// <summary>
        /// 0 to enable PMTU, 552-1500 to start PMTU with a lower MTU
        /// </summary>
        [Output("mtu")]
        public Output<int?> Mtu { get; private set; } = null!;

        /// <summary>
        /// Mist Edge cluster IDs that host this Mist Tunnel
        /// </summary>
        [Output("mxclusterIds")]
        public Output<ImmutableArray<string>> MxclusterIds { get; private set; } = null!;

        /// <summary>
        /// Display name of the Mist Tunnel
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Identifier of the org that owns the Mist Tunnel
        /// </summary>
        [Output("orgId")]
        public Output<string> OrgId { get; private set; } = null!;

        /// <summary>
        /// Encapsulation protocol used for the Mist Tunnel
        /// </summary>
        [Output("protocol")]
        public Output<string?> Protocol { get; private set; } = null!;

        /// <summary>
        /// List of VLAN IDs carried by this Mist Tunnel
        /// </summary>
        [Output("vlanIds")]
        public Output<ImmutableArray<int>> VlanIds { get; private set; } = null!;


        /// <summary>
        /// Create a Mxtunnel resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Mxtunnel(string name, MxtunnelArgs args, CustomResourceOptions? options = null)
            : base("junipermist:org/mxtunnel:Mxtunnel", name, args ?? new MxtunnelArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Mxtunnel(string name, Input<string> id, MxtunnelState? state = null, CustomResourceOptions? options = null)
            : base("junipermist:org/mxtunnel:Mxtunnel", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumi/pulumi-junipermist",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Mxtunnel resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Mxtunnel Get(string name, Input<string> id, MxtunnelState? state = null, CustomResourceOptions? options = null)
        {
            return new Mxtunnel(name, id, state, options);
        }
    }

    public sealed class MxtunnelArgs : global::Pulumi.ResourceArgs
    {
        [Input("anchorMxtunnelIds")]
        private InputList<string>? _anchorMxtunnelIds;

        /// <summary>
        /// IDs of anchor Mist Tunnels used for edge-to-edge tunnel formation
        /// </summary>
        public InputList<string> AnchorMxtunnelIds
        {
            get => _anchorMxtunnelIds ?? (_anchorMxtunnelIds = new InputList<string>());
            set => _anchorMxtunnelIds = value;
        }

        /// <summary>
        /// Preemption behavior for restoring preferred tunnel peers after failover
        /// </summary>
        [Input("autoPreemption")]
        public Input<Inputs.MxtunnelAutoPreemptionArgs>? AutoPreemption { get; set; }

        /// <summary>
        /// In seconds, used as heartbeat to detect if a tunnel is alive. AP will try another peer after missing N hellos specified by `HelloRetries`.
        /// </summary>
        [Input("helloInterval")]
        public Input<int>? HelloInterval { get; set; }

        /// <summary>
        /// Number of missed hello heartbeats before an AP tries another tunnel peer
        /// </summary>
        [Input("helloRetries")]
        public Input<int>? HelloRetries { get; set; }

        /// <summary>
        /// Security settings for IPsec support on this Mist Tunnel
        /// </summary>
        [Input("ipsec")]
        public Input<Inputs.MxtunnelIpsecArgs>? Ipsec { get; set; }

        /// <summary>
        /// 0 to enable PMTU, 552-1500 to start PMTU with a lower MTU
        /// </summary>
        [Input("mtu")]
        public Input<int>? Mtu { get; set; }

        [Input("mxclusterIds")]
        private InputList<string>? _mxclusterIds;

        /// <summary>
        /// Mist Edge cluster IDs that host this Mist Tunnel
        /// </summary>
        public InputList<string> MxclusterIds
        {
            get => _mxclusterIds ?? (_mxclusterIds = new InputList<string>());
            set => _mxclusterIds = value;
        }

        /// <summary>
        /// Display name of the Mist Tunnel
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Identifier of the org that owns the Mist Tunnel
        /// </summary>
        [Input("orgId", required: true)]
        public Input<string> OrgId { get; set; } = null!;

        /// <summary>
        /// Encapsulation protocol used for the Mist Tunnel
        /// </summary>
        [Input("protocol")]
        public Input<string>? Protocol { get; set; }

        [Input("vlanIds")]
        private InputList<int>? _vlanIds;

        /// <summary>
        /// List of VLAN IDs carried by this Mist Tunnel
        /// </summary>
        public InputList<int> VlanIds
        {
            get => _vlanIds ?? (_vlanIds = new InputList<int>());
            set => _vlanIds = value;
        }

        public MxtunnelArgs()
        {
        }
        public static new MxtunnelArgs Empty => new MxtunnelArgs();
    }

    public sealed class MxtunnelState : global::Pulumi.ResourceArgs
    {
        [Input("anchorMxtunnelIds")]
        private InputList<string>? _anchorMxtunnelIds;

        /// <summary>
        /// IDs of anchor Mist Tunnels used for edge-to-edge tunnel formation
        /// </summary>
        public InputList<string> AnchorMxtunnelIds
        {
            get => _anchorMxtunnelIds ?? (_anchorMxtunnelIds = new InputList<string>());
            set => _anchorMxtunnelIds = value;
        }

        /// <summary>
        /// Preemption behavior for restoring preferred tunnel peers after failover
        /// </summary>
        [Input("autoPreemption")]
        public Input<Inputs.MxtunnelAutoPreemptionGetArgs>? AutoPreemption { get; set; }

        /// <summary>
        /// In seconds, used as heartbeat to detect if a tunnel is alive. AP will try another peer after missing N hellos specified by `HelloRetries`.
        /// </summary>
        [Input("helloInterval")]
        public Input<int>? HelloInterval { get; set; }

        /// <summary>
        /// Number of missed hello heartbeats before an AP tries another tunnel peer
        /// </summary>
        [Input("helloRetries")]
        public Input<int>? HelloRetries { get; set; }

        /// <summary>
        /// Security settings for IPsec support on this Mist Tunnel
        /// </summary>
        [Input("ipsec")]
        public Input<Inputs.MxtunnelIpsecGetArgs>? Ipsec { get; set; }

        /// <summary>
        /// 0 to enable PMTU, 552-1500 to start PMTU with a lower MTU
        /// </summary>
        [Input("mtu")]
        public Input<int>? Mtu { get; set; }

        [Input("mxclusterIds")]
        private InputList<string>? _mxclusterIds;

        /// <summary>
        /// Mist Edge cluster IDs that host this Mist Tunnel
        /// </summary>
        public InputList<string> MxclusterIds
        {
            get => _mxclusterIds ?? (_mxclusterIds = new InputList<string>());
            set => _mxclusterIds = value;
        }

        /// <summary>
        /// Display name of the Mist Tunnel
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Identifier of the org that owns the Mist Tunnel
        /// </summary>
        [Input("orgId")]
        public Input<string>? OrgId { get; set; }

        /// <summary>
        /// Encapsulation protocol used for the Mist Tunnel
        /// </summary>
        [Input("protocol")]
        public Input<string>? Protocol { get; set; }

        [Input("vlanIds")]
        private InputList<int>? _vlanIds;

        /// <summary>
        /// List of VLAN IDs carried by this Mist Tunnel
        /// </summary>
        public InputList<int> VlanIds
        {
            get => _vlanIds ?? (_vlanIds = new InputList<int>());
            set => _vlanIds = value;
        }

        public MxtunnelState()
        {
        }
        public static new MxtunnelState Empty => new MxtunnelState();
    }
}
