// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.junipermist.org.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SsoRolePrivilege {
    /**
     * @return access permissions. enum: `admin`, `helpdesk`, `installer`, `read`, `write`
     * 
     */
    private String role;
    /**
     * @return enum: `org`, `site`, `sitegroup`
     * 
     */
    private String scope;
    /**
     * @return Required if `scope`==`site`
     * 
     */
    private @Nullable String siteId;
    /**
     * @return Required if `scope`==`sitegroup`
     * 
     */
    private @Nullable String sitegroupId;
    /**
     * @return Custom roles restrict Org users to specific UI views. This is useful for limiting UI access of Org users. Custom roles restrict Org users to specific UI views. This is useful for limiting UI access of Org users.\
     * You can define custom roles by adding the `views` attribute along with `role` when assigning privileges.\
     * Below are the list of supported UI views. Note that this is UI only feature.
     * 
     *   | UI View | Required Role | Description |
     *   | --- | --- | --- |
     *   | `reporting` | `read` | full access to all analytics tools |
     *   | `marketing` | `read` | can view analytics and location maps |
     *   | `superObserver` | `read` | can view all the organization except the subscription page |
     *   | `location` | `write` | can view and manage location maps, can view analytics |
     *   | `security` | `write` | can view and manage site labels, policies and security |
     *   | `switchAdmin` | `helpdesk` | can view and manage Switch ports, can view wired clients |
     *   | `mxedgeAdmin` | `admin` | can view and manage Mist edges and Mist tunnels |
     *   | `lobbyAdmin` | `admin` | full access to Org and Site Pre-shared keys |
     * 
     */
    private @Nullable List<String> views;

    private SsoRolePrivilege() {}
    /**
     * @return access permissions. enum: `admin`, `helpdesk`, `installer`, `read`, `write`
     * 
     */
    public String role() {
        return this.role;
    }
    /**
     * @return enum: `org`, `site`, `sitegroup`
     * 
     */
    public String scope() {
        return this.scope;
    }
    /**
     * @return Required if `scope`==`site`
     * 
     */
    public Optional<String> siteId() {
        return Optional.ofNullable(this.siteId);
    }
    /**
     * @return Required if `scope`==`sitegroup`
     * 
     */
    public Optional<String> sitegroupId() {
        return Optional.ofNullable(this.sitegroupId);
    }
    /**
     * @return Custom roles restrict Org users to specific UI views. This is useful for limiting UI access of Org users. Custom roles restrict Org users to specific UI views. This is useful for limiting UI access of Org users.\
     * You can define custom roles by adding the `views` attribute along with `role` when assigning privileges.\
     * Below are the list of supported UI views. Note that this is UI only feature.
     * 
     *   | UI View | Required Role | Description |
     *   | --- | --- | --- |
     *   | `reporting` | `read` | full access to all analytics tools |
     *   | `marketing` | `read` | can view analytics and location maps |
     *   | `superObserver` | `read` | can view all the organization except the subscription page |
     *   | `location` | `write` | can view and manage location maps, can view analytics |
     *   | `security` | `write` | can view and manage site labels, policies and security |
     *   | `switchAdmin` | `helpdesk` | can view and manage Switch ports, can view wired clients |
     *   | `mxedgeAdmin` | `admin` | can view and manage Mist edges and Mist tunnels |
     *   | `lobbyAdmin` | `admin` | full access to Org and Site Pre-shared keys |
     * 
     */
    public List<String> views() {
        return this.views == null ? List.of() : this.views;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SsoRolePrivilege defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String role;
        private String scope;
        private @Nullable String siteId;
        private @Nullable String sitegroupId;
        private @Nullable List<String> views;
        public Builder() {}
        public Builder(SsoRolePrivilege defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.role = defaults.role;
    	      this.scope = defaults.scope;
    	      this.siteId = defaults.siteId;
    	      this.sitegroupId = defaults.sitegroupId;
    	      this.views = defaults.views;
        }

        @CustomType.Setter
        public Builder role(String role) {
            if (role == null) {
              throw new MissingRequiredPropertyException("SsoRolePrivilege", "role");
            }
            this.role = role;
            return this;
        }
        @CustomType.Setter
        public Builder scope(String scope) {
            if (scope == null) {
              throw new MissingRequiredPropertyException("SsoRolePrivilege", "scope");
            }
            this.scope = scope;
            return this;
        }
        @CustomType.Setter
        public Builder siteId(@Nullable String siteId) {

            this.siteId = siteId;
            return this;
        }
        @CustomType.Setter
        public Builder sitegroupId(@Nullable String sitegroupId) {

            this.sitegroupId = sitegroupId;
            return this;
        }
        @CustomType.Setter
        public Builder views(@Nullable List<String> views) {

            this.views = views;
            return this;
        }
        public Builder views(String... views) {
            return views(List.of(views));
        }
        public SsoRolePrivilege build() {
            final var _resultValue = new SsoRolePrivilege();
            _resultValue.role = role;
            _resultValue.scope = scope;
            _resultValue.siteId = siteId;
            _resultValue.sitegroupId = sitegroupId;
            _resultValue.views = views;
            return _resultValue;
        }
    }
}
