// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Device.Outputs
{

    [OutputType]
    public sealed class GatewayPortConfigWanProbeOverride
    {
        /// <summary>
        /// List of hostnames used as probe destinations; applicable for both IPv4 and IPv6
        /// </summary>
        public readonly ImmutableArray<string> Hostnames;
        /// <summary>
        /// HTTP probe settings; success from any ICMP or HTTP probe indicates the WAN is up
        /// </summary>
        public readonly Outputs.GatewayPortConfigWanProbeOverrideHttp? Http;
        /// <summary>
        /// List of IPv6 probe host addresses used by this WAN override
        /// </summary>
        public readonly ImmutableArray<string> Ip6s;
        /// <summary>
        /// List of IPv4 probe host addresses used by this WAN override
        /// </summary>
        public readonly ImmutableArray<string> Ips;
        /// <summary>
        /// WAN probe profile used for health checks on this port
        /// </summary>
        public readonly string? ProbeProfile;

        [OutputConstructor]
        private GatewayPortConfigWanProbeOverride(
            ImmutableArray<string> hostnames,

            Outputs.GatewayPortConfigWanProbeOverrideHttp? http,

            ImmutableArray<string> ip6s,

            ImmutableArray<string> ips,

            string? probeProfile)
        {
            Hostnames = hostnames;
            Http = http;
            Ip6s = ip6s;
            Ips = ips;
            ProbeProfile = probeProfile;
        }
    }
}
