// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Device.Outputs
{

    [OutputType]
    public sealed class SwitchVrfInstancesExtraRoutes6
    {
        /// <summary>
        /// Next-hop address
        /// </summary>
        public readonly string? Via;

        [OutputConstructor]
        private SwitchVrfInstancesExtraRoutes6(string? via)
        {
            Via = via;
        }
    }
}
