// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Device.Outputs
{

    [OutputType]
    public sealed class SwitchOspfConfigAreas
    {
        /// <summary>
        /// Disable OSPF summary routes for this area
        /// </summary>
        public readonly bool? NoSummary;

        [OutputConstructor]
        private SwitchOspfConfigAreas(bool? noSummary)
        {
            NoSummary = noSummary;
        }
    }
}
