// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JuniperMist.Device.Outputs
{

    [OutputType]
    public sealed class SwitchOspfConfig
    {
        /// <summary>
        /// Property key is the area name. Defines the OSPF areas configured on the switch.
        /// </summary>
        public readonly ImmutableDictionary<string, Outputs.SwitchOspfConfigAreas>? Areas;
        /// <summary>
        /// Enable OSPF on the switch
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// optional, for basic scenario, `import_policy` can be specified and can be applied to all networks in all areas if not explicitly specified
        /// </summary>
        public readonly string? ExportPolicy;
        /// <summary>
        /// optional, for basic scenario, `import_policy` can be specified and can be applied to all networks in all areas if not explicitly specified
        /// </summary>
        public readonly string? ImportPolicy;
        public readonly string? ReferenceBandwidth;

        [OutputConstructor]
        private SwitchOspfConfig(
            ImmutableDictionary<string, Outputs.SwitchOspfConfigAreas>? areas,

            bool? enabled,

            string? exportPolicy,

            string? importPolicy,

            string? referenceBandwidth)
        {
            Areas = areas;
            Enabled = enabled;
            ExportPolicy = exportPolicy;
            ImportPolicy = importPolicy;
            ReferenceBandwidth = referenceBandwidth;
        }
    }
}
