# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'UpgradeDeviceAutoUpgradeStatArgs',
    'UpgradeDeviceAutoUpgradeStatArgsDict',
    'UpgradeDeviceFwupdateArgs',
    'UpgradeDeviceFwupdateArgsDict',
]

class UpgradeDeviceAutoUpgradeStatArgsDict(TypedDict):
    lastcheck: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    Time when the device last checked for auto-upgrade, in epoch seconds
    """

@pulumi.input_type
class UpgradeDeviceAutoUpgradeStatArgs:
    def __init__(__self__, *,
                 lastcheck: pulumi.Input[Optional[_builtins.int]] = None):
        """
        :param pulumi.Input[_builtins.int] lastcheck: Time when the device last checked for auto-upgrade, in epoch seconds
        """
        if lastcheck is not None:
            pulumi.set(__self__, "lastcheck", lastcheck)

    @_builtins.property
    @pulumi.getter
    def lastcheck(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Time when the device last checked for auto-upgrade, in epoch seconds
        """
        return pulumi.get(self, "lastcheck")

    @lastcheck.setter
    def lastcheck(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "lastcheck", value)


class UpgradeDeviceFwupdateArgsDict(TypedDict):
    progress: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    Firmware update progress percentage, or null when unavailable
    """
    status: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Current firmware update status
    """
    status_id: NotRequired[pulumi.Input[Optional[_builtins.int]]]
    """
    Numeric firmware update status identifier
    """
    timestamp: NotRequired[pulumi.Input[Optional[_builtins.float]]]
    """
    Time when the firmware update status was last updated
    """
    will_retry: NotRequired[pulumi.Input[Optional[_builtins.bool]]]
    """
    Whether the firmware update process will retry after the current status
    """

@pulumi.input_type
class UpgradeDeviceFwupdateArgs:
    def __init__(__self__, *,
                 progress: pulumi.Input[Optional[_builtins.int]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 status_id: pulumi.Input[Optional[_builtins.int]] = None,
                 timestamp: pulumi.Input[Optional[_builtins.float]] = None,
                 will_retry: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        :param pulumi.Input[_builtins.int] progress: Firmware update progress percentage, or null when unavailable
        :param pulumi.Input[_builtins.str] status: Current firmware update status
        :param pulumi.Input[_builtins.int] status_id: Numeric firmware update status identifier
        :param pulumi.Input[_builtins.float] timestamp: Time when the firmware update status was last updated
        :param pulumi.Input[_builtins.bool] will_retry: Whether the firmware update process will retry after the current status
        """
        if progress is not None:
            pulumi.set(__self__, "progress", progress)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if status_id is not None:
            pulumi.set(__self__, "status_id", status_id)
        if timestamp is not None:
            pulumi.set(__self__, "timestamp", timestamp)
        if will_retry is not None:
            pulumi.set(__self__, "will_retry", will_retry)

    @_builtins.property
    @pulumi.getter
    def progress(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Firmware update progress percentage, or null when unavailable
        """
        return pulumi.get(self, "progress")

    @progress.setter
    def progress(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "progress", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Current firmware update status
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter(name="statusId")
    def status_id(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Numeric firmware update status identifier
        """
        return pulumi.get(self, "status_id")

    @status_id.setter
    def status_id(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "status_id", value)

    @_builtins.property
    @pulumi.getter
    def timestamp(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Time when the firmware update status was last updated
        """
        return pulumi.get(self, "timestamp")

    @timestamp.setter
    def timestamp(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "timestamp", value)

    @_builtins.property
    @pulumi.getter(name="willRetry")
    def will_retry(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the firmware update process will retry after the current status
        """
        return pulumi.get(self, "will_retry")

    @will_retry.setter
    def will_retry(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "will_retry", value)


